### ISSUE TITLE
command line input 

### ISSUE THREAD

**Issue by erviker** [djfun/audio-visualizer-python#10]
it would be awesome if it was possible to run this as an commmand line tool. 

something like this
python3 main.py -i input.mp3 -o output.mp4 -b background.png -t "The text"

**Comment by thercast** [comment]
Just wanted to chime in that I am a podcaster with an audio-only show that would really like to use this in an automated publishing workflow!

**Comment by thercast** [comment]
Just a quick check to see if there are any updates to this?

**Comment by djfun** [comment]
Yes, I have some free time now, so I can work on this again.
I assume, you don't want to have all the QT stuff installed if you only want to run this from the command line. It might be easier to create a separate python file for that instead of creating a switching mechanism in main.py

**Comment by thercast** [comment]
Hey thanks for the update.  Yeah I'm interested in using it on command line
since it will be part of a overall pipeline to publish my podcasts.

**Comment by djfun** [comment]
after looking at the code, it seems we have 2 options:
1. keep the dependencies on PyQt4 even for command line execution (and still have the benefits of using QSettings and QThread)
2. refactor video_thread.py to have a version, that does not need to be run as a QThread and find a solution to read the settings file without QT, but do not require to install PyQt4 if you don't need the GUI at all

is it a problem for your use case to have PyQt4 installed?

**Comment by thercast** [comment]
That should be fine as long as it is not difficultto install on say ubuntu
or arch linux

**Comment by djfun** [comment]
I made a commit to the feature-commandline branch (https://github.com/djfun/audio-visualizer-python/tree/feature-commandline). It is still experimental, so please try using it and report back, what does not work/is still missing

**Comment by thercast** [comment]
I gave this a shot and was not able to get a video created on the command line.  I'm running this on an Ubuntu 14.04 machine with all the pre-requisites installed and verified that the GUI version works without a problem.  Here's the full command I tried to run and the output:

### Command 
```
python3 main.py \
-i /mythtv_extra/r_podcast_source/media_files/rpodcast_promo/rpodcast_promo_v2.mp3 \
-o /mythtv_extra/r_podcast_source/audio_visualizer/promo_batch.mp4 \
--background=/mythtv_extra/r_podcast_source/r_website_files/header_image_files/banner_background_only.png \
-t "Test from command line"
```

### Output
```
Traceback (most recent call last):
  File "main.py", line 240, in <module>
    command = Command()
  File "main.py", line 33, in __init__
    self.fontsize = int(self.settings.value("fontSize"))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```
So it seems that the parameter values for title font and the various options for the title need to be specified.  When I ran the GUI version I saw that a `settings.ini` was created with values of the input dir, output dir, and background dir populated in a `[General]` section, but nothing about the title parameters.  When I examined `main.py` it appears that the script is trying t grab these title parameters from the `settings.ini` file but of course they are not in the file.  

One other observation: When I tried running this command in an SSH session connected to this server, I got an error about no X server installed.  Is this a consequence of the pyQt4 dependency?  I was hoping to run this in an SSH session (right now I connect to the desktop of the server via a VNC client since the server is also a media box).  For the above command I ran it within the VNC session so I did not receive the x server error.

**Comment by djfun** [comment]
thanks for the feedback, I'll look into the issues. The settings file problem should be pretty easy to fix. For the pyQt4 and X Server problem I will need to read some more documentation I guess.

**Comment by djfun** [comment]
command line mode should now run without X server (it does so at least in my tests), I also added default values when there is no settings.ini or if there are missing values in that file. You can provide a font name with a new parameter, which should get saved to the settings.ini for any following runs.

**Comment by thercast** [comment]
Just ran another test with the updates and it worked flawlessly in the ssh session.  My only minor comment is it would be nice to have command line parameters for the additional title parameters that are currently offered in the gui (x position, y position, alignment).

**Comment by djfun** [comment]
added the missing parameters and merged into master
