### ISSUE TITLE
Expand functionality, add more visualization options

### ISSUE THREAD

**Issue by djfun** [djfun/audio-visualizer-python#15]
As introduced in https://github.com/djfun/audio-visualizer-python/issues/9#issuecomment-303070367, the idea is to have the ability to add more visualization options.
I made a UI mockup with http://pencil.evolus.vn/ how such a system could look like:
![audio-visualizer-mockup1](https://cloud.githubusercontent.com/assets/609660/26398735/b1a5aaaa-407a-11e7-8b35-af6f85cf1349.png)
If someone wants to extend this mockup, I can upload the .epgz file.

I would like to have some thoughts, opinions, new ideas on this suggestion and possibly already people who would offer to help with the programming.

**Comment by rikai** [comment]
Seems like a great start with decent potential for growth to me, but i did also just wake up, so i'll think on it some more. ;)

**Comment by djfun** [comment]
ok, cool!
thanks btw. for featuring this project in the podcast

**Comment by thercast** [comment]
While this comment is more about the backend and other visualization options, I was having discussions with @rikai on another channel about additional visualization ideas.  He found a powerful music visualization suite called [projectM](http://projectm-visualizer.github.io/projectm/) which mimics the [milkdrop](https://en.wikipedia.org/wiki/MilkDrop) visualization tool used in the classic WinAmp player of yesteryear.  I've begun a [dialog](https://github.com/projectM-visualizer/projectm/issues/10) with their team on how this framework could be invoked and general guidance on creating wrappers to it (such as a python wrapper), so that eventually it could be called from this visualizer.   This is all just a suggestion, and if there is a way you could accomplish a similar thing in this audio visualizer directly then that would likely be a more logical path forward.

**Comment by djfun** [comment]
I think the visualizations of projectM could be a great component/plugin in this new extended tool. The user could add this projectM component and then for example add a text over it.
The current visualization in audio-visualizer-python, the moving bars, is created frame by frame as PIL images and then send via pipe to ffmpeg. So I think a python wrapper for projectM (or any other visualization tool we would want to have a plugin for) would need to be able to either send the visualization data as single frames, then we could do the compositing with other components like text in python, or it could also send it as full video, which we could then either read and composite in python or let ffmpeg do the compositing.
If you have any more questions regarding the technical side of this tool, feel free to ask.
We could even set up a telegram,threema,irc,.. group chat if that makes it easier to discuss/coordinate.

**Comment by rikai** [comment]
@thercast We did discuss this a bit in #9 already... Probably should create some kind of tracking issue for the idea.

@djfun I've personally got telegram and discord open all the time on my desktop and phone, so either of those would work fine for me, though i'm more of a 'concepts' guy that a real coder. 👍

**Comment by tassaron2** [comment]
I like that mock-up. I notice it says the preview is "possibly interactive", which is interesting. I was thinking it would be nice to be able to specify the title text position by clicking the preview itself, instead of typing arcane numbers into text fields. :) Is that something like what you meant?

I would love to help with the programming side. However I don't know if I'm a good enough programmer to make a plugin system... I could try but it sounds hard :)

**Comment by djfun** [comment]
Yes, I was thinking of being able to drag the active element in the preview window to reposition them and possibly changing their size.

When I made this mockup, I was not entirely satisfied with the positioning of the progress bar either. Maybe we want to move the select music etc. buttons over where there is still blank space under the add/remove component buttons. Then the space for options of components could be the entire width of the window.
What I don't want is, if it is avoidable, that you need to have the program in full screen on a laptop monitor. The preview should be able to grow, if the window size gets bigger.

**Comment by djfun** [comment]
@tassaron2 @thercast There is now a telegram group at https://t.me/joinchat/AAAAAA2PGPf1Us18F49_ag to coordinate the project and exchange ideas

**Comment by tassaron2** [comment]
Hm. I think I like the mock-up better because it splits the window into mandatory settings on one side and component-related things on the other side. It seems nicely organized in that way. I suppose if you put those buttons with the components, then you could shrink the window significantly by hiding the component options since they would be on their own row... But then certain 'mandatory' features of components would be hidden, like the title text.

So a possible design could be... preview window in top-left pane; all mandatory options in the top-right pane, starting with the Main options (select music, background etc.), then an area for adding/removing components, then the mandatory options of components organized by subheading; and the bottom pane is a big area for optional options (heh), again organized by subheading. The optional area could then have the Main optional options (frame size, etc) followed by the component options in order.

This way all the extra settings could be hidden away behind a button if so desired, and the window would be a lot smaller until someone needs to change the frame size or colours... But that might be coming at the cost of being a more confusing design since it splits the settings up. I don't know.

Components need to have a standard definition file giving them a name, a path to plugin code or something, and define what the mandatory and optional settings are... And any setting could have a default state defined for if it, which would be added to the form in audio-visualizer when it's constructed. I don't know what the best method for actually communicating with the plugin/component code would be, though. The components could simply be Python modules instead of requiring a definition file. Hmm.

I would also like to implement the ability to drag and drop files into the fields, so you can use a file manager to select files. I've tried adding that already and it seems easy.

**Comment by tassaron2** [comment]
![sketch](https://cloud.githubusercontent.com/assets/9700496/26475532/21f730c4-4186-11e7-8175-0b6e371cc53d.png)
I made a mockup of what I said above, but this makes the window quite long. I'm not too sure about that. However it shows what I meant by having one section of the window hideable underneath the horizontal separator, with the mandatory settings separated from the optional settings. (The only mandatory setting here would be the title text.)

Instead of a bunch of little boxes, the settings could be in a tabbed interface. It may look tidier that way.

**Comment by tassaron2** [comment]
![sketch2](https://cloud.githubusercontent.com/assets/9700496/26477642/18e744f6-4195-11e7-834a-33fc2d30e1a7.png)

Technically the components add/remove area could itself be considered an advanced setting and hidden, if the button is moved to the left. The grey separator marks where the window could be shrunk to. This would make the window less wide.

**Comment by IamDH4** [comment]
![image](https://cloud.githubusercontent.com/assets/9543868/26522362/a0512328-42c4-11e7-9e22-594206162549.png)

This is my take on it, based alot on the submission by @djfun.

**Comment by IamDH4** [comment]
![mainwindow_020](https://cloud.githubusercontent.com/assets/9543868/26522678/34255258-42cb-11e7-9272-c0b522a2ca2a.png)

**Comment by IamDH4** [comment]
Current iteration of the new UI has been pushed to the `newgui` branch. Several components are still a work in progress. Need to change the layout for project and preset buttons. Some backend code to implement. We are looking for feedback on the design.

Thanks!

![Uploading Audio Visualizer_049.png…]()

**Comment by IamDH4** [comment]
Please dedicated this thread to discussions about the GUI only, projectM has it's own thread at #22. If you have suggestions for other visualization libraries please create a new issue.

**Comment by IamDH4** [comment]
This is the latest iteration on the design. Many new features implemented. I am considering this issue closed. Please report bugs, feedback, and feature requests by creating a new issue. We are currently on a feature freeze until we hit our [ first milestone](https://github.com/djfun/audio-visualizer-python/milestone/1).

![audio visualizer - my project_086](https://user-images.githubusercontent.com/9543868/27469314-81ea9d9c-57b4-11e7-993e-8951809c9477.png)
