### ISSUE TITLE
Add the ability to specify more parameters.

### ISSUE THREAD

**Issue by rikai** [djfun/audio-visualizer-python#7]
From the discussion in PR #4:

Being able to specify the frame size, fps, audio and video codecs and bitrates, format & more makes sense and honestly probably shouldn't be hardcoded at all.

Additionally, I think a dialog to specify custom additional parameters might be nice to have as well.

There's probably some crossover with #6 and this issue as well.

**Comment by IamDH4** [comment]
Working swiftly towards this goal. Most of the ground work has been layed on the backend. Some of it has already been implemented in the GUI.

eaee0ab233709c18324dbb25f38b59c95c447e3c
fe13268a841d3b4d45f33359abb81993d990772c
75c1c65c9d63515a1488b63e9df9971984e1f7e8
d9a5f2dd34c0bf14bfc99b58183b00d43217d889
c21d6f5ea7c6d33e2ded44b823d2dbb5b9384d78
1eeb763dc31343762f827f9610eb464cce4fd7cc

**Comment by tassaron2** [comment]
`feature-newgui` now contains all these features except for fps (still hardcoded at 30) and custom parameters. Those features will be added in the next milestone, so this issue will remain open to track them and be added to that milestone when it is created.

**Comment by tassaron** [comment]
I am going to close this issue because I don't really have motivation to implement higher framerates or any other custom parameters mentioned in the discussion so far, at the current time.

If someone wants to see these features implemented, please open a more specific issue about the new option you want. I might work on it later if I know someone wants it
