### ISSUE TITLE
Can't use projects from commandline

### ISSUE THREAD

**Issue by 4aiman** [djfun/audio-visualizer-python#78]
Hello,

I've been trying to automate audio processing by using a project that I've saved from GUI.
I took me a while to understand how to properly put project path into the bash command, but when I finally did, I ran into this issue:
```
Traceback:
  File "audio-visualizer-python/lib/python3.10/site-packages/avp/component.py", line 85, in propertiesWrapper
    return func(self)

  File "audio-visualizer-python/lib/python3.10/site-packages/avp/components/video.py", line 70, in properties
    outputFile = str(self.parent.args.output)
```

The relevant piece of code is this one:
![изображение](https://github.com/user-attachments/assets/b31534b3-bf80-4172-b667-8bd311dc616e)

Long story short, to be able to batch process my files I have:
- commented out the lines 68-69 in the `video.py` file where `self.parent.args` were being read.
- added the 66 line in the same file to declare an "empty" `outputFile` variable.

I'm too vaguely acquainted with Python to comprehend what I did in there on the "architectural level" .
That's the reason behind why this isn't a pull request: I just don't know what else I've broken with these changes.

I hope that someone more proficient in Python than me would one day take a look at this and make a proper fix.

**Comment by tassaron** [comment]
Took me a bit to remember how this code works... Now I've figured it out.

The Video component tries to ensure that it's not using the same video as the output path, and it tries to do that by checking a widget in the GUI (which isn't really how it should be done, but it's what it is). If it doesn't find the widget because the GUI doesn't exist, it assumes it can check the commandline arguments. Problem is: the arguments are not actually stored anywhere, just local to the function that parses them. And this wouldn't have been correct anyway, because it's possible to use the output-path saved in the project file, which would result in a blank argument _and_ no GUI widget.

The "best" solution would probably be some redesign so the output-path is officially available for components to check before the export begins, but I'd rather not add more edge cases to the code. Eventually I'd like to make the execution flow more obvious. For now, I will make it only check for this error in GUI mode (I don't think it's likely to occur by accident, anyway). That's effectively the same as your solution.

Thanks for reporting this! :grin:
